version: '3'

services:

  website:
    image: alexvarney/portfolio:latest
    container_name: Portfolio
    entrypoint: 'npx serve -s build'
    expose:
      - "80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=varney.me,www.varney.me
      - LETSENCRYPT_HOST=varney.me,www.varney.me
      - LETSENCRYPT_EMAIL=alex@varney.me
    networks:
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy